# Enable C++ support
language: cpp

os:
  - osx
  - linux

sudo: required
dist: trusty

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
      sudo apt-get update -qq
    fi

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      brew update > /dev/null
      brew install llvm
      export PATH="/usr/local/opt/llvm/bin:$PATH"
      brew install qt5      
      export QTDIR="/usr/local/opt/qt5"
    fi
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      sudo apt-get -y install qt55[QTPACKAGE]
    fi
  - cd ..
  - git clone -b devel https://github.com/cnr-isti-vclab/vcglib.git
  - cd meshlab

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then PATH="/usr/local/opt/llvm/bin:$PATH"          ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then which clang             ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then ln -s /usr/local/opt/llvm/bin/clang /usr/local/opt/llvm/bin/clang++-mp-3.9       ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then PATH="$QTDIR/bin:$PATH"          ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then LDFLAGS=-L$QTDIR/lib            ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then CPPFLAGS=-I$QTDIR/include        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux"   ]]; then source /opt/qt55/bin/qt55-env.sh        ;fi
  - cd src
  - cd external
  - qmake --version
  - qmake 
  - make
  - cd ..
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then qmake "QMAKE_LFLAGS+=-L/usr/local/opt/llvm/lib -lomp" meshlab_full.pro         ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then qmake meshlab_full.pro         ;fi
  - make 
